#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Thesis  # The title of the book. Will be placed in the left navbar.
author                      : A S Sahasranamam  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo2.png  # A path to the book logo


repository:
  url: https://github.com/assahasranamam/thesis
  branch: primary  # An optional branch, defaults to `master`
